# # -*- coding: utf-8 -*-
# """FOSSILITA

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1ID1DF0igpzD787Z_0haW6zuQm848FRMZ

# Fossa Séptica
# """

# Edificacao = 'Fabrica em Geral' #@param ["Selecione...", "Residencia", "Alojamento Provisorio" , "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais" , "Escolas ou locais de longa permanencia" , "Bares", "Restaurantes e similares", "Cinemas, teatros e locais de curta permanencia" , "Sanitarios Publicos" ]

# if (Edificacao == "Residencia", "Alojamento Provisorio", "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais", "Escolas ou locais de longa permanencia"): 
#   Numero_pessoas =  5#@param {type:"number"}

# elif (Edificacao == "Restaurantes e similares", "Bares"):
#   Numero_refeicoes = 5#@param {type:"number"}

# elif (Edificacao == "Cinema, teatros e locais de curta permanencia"):
#   Numero_lugares = 5#@param {type:"number"}

# elif (Edificacao == "Sanitarios Publicos"):
#   Numero_bacias_sanitarias = 5#@param {type:"number"}


# Temperatura_media =  17#@param {type:"number"}
# Temperatura_media = int(Temperatura_media)

# Intervalo_limpeza =  5#@param {type:"number"}
# Intervalo_limpeza = int(Intervalo_limpeza)

# print("Voce escolheu a opcao " + Edificacao)


# C = "Verifique as opcoes" 
# #Contribuição de Esgoto por Unidade

# T = "Valor Invalido"
# #Tempo de detenção

# Lf = "Valor Invalido" 
# #Contribuição de Lodo Fresco

# Cd = "Valor Invalido"
# #Contribuição Diária

# K = "Valor Invalido"
# #Taxa de acumulação de Lodo Fresco

# Np = Numero_pessoas

# if(Edificacao == "Residencia"):
#   C = 200
#   Lf = 1

# elif(Edificacao == "Alojamento Provisorio"):
#   C = 80
#   Lf = 1

# elif(Edificacao == "Fabrica em Geral"):
#   C = 70
#   Lf = 0.3

# elif(Edificacao == "Escritorio"):
#   C = 50
#   Lf = 0.2

# elif(Edificacao == "Edificios Publicos ou Comerciais"):
#   C = 50
#   Lf = 0.2

# elif(Edificacao == "Escolas ou locais de longa permanencia"):
#   C = 50
#   Lf = 0.2

# elif(Edificacao == "Bares"):
#   C = 6
#   Lf = 0.1

# elif(Edificacao == "Restaurantes e similares"):
#   C = 25
#   Lf = 0.1

# elif(Edificacao == "Cinemas, teatros e locais de curta permanencia"):
#   C = 2
#   Lf = 0.02

# elif(Edificacao == "Sanitarios Publicos"):
#   C = 480
#   Lf = 4

# Cd = Np * C

# if (Cd <= 1500):
#   T = 24

# elif (Cd >= 1501 and Cd <= 3000):
#   T = 22

# elif (Cd >= 3001 and Cd <= 4500):
#   T = 20

# elif (Cd >= 4501 and Cd <= 6000):
#   T = 18

# elif (Cd >= 6001 and Cd <= 7500):
#   T = 16

# elif (Cd >= 7501 and Cd <= 9000):
#   T = 14

# elif (Cd >= 9001):
#   T = 12







# if (Temperatura_media < 10 and Intervalo_limpeza == 1):
#   K = 94

# elif (Temperatura_media < 10 and Intervalo_limpeza == 2):
#   K = 134

# elif (Temperatura_media < 10 and Intervalo_limpeza == 3):
#   K = 174

# elif (Temperatura_media < 10 and Intervalo_limpeza == 4):
#   K = 214

# elif (Temperatura_media < 10 and Intervalo_limpeza == 5):
#   K = 254



# elif (Temperatura_media >= 11 and Temperatura_media <= 20 and Intervalo_limpeza == 1):
#   K = 65

# elif (Temperatura_media >= 11 and Temperatura_media <= 20 and Intervalo_limpeza == 2):
#   K = 105

# elif (Temperatura_media >= 11 and Temperatura_media <= 20 and Intervalo_limpeza == 3):
#   K = 145

# elif (Temperatura_media >= 11 and Temperatura_media <= 20 and Intervalo_limpeza == 4):
#   K = 185

# elif (Temperatura_media >= 11 and Temperatura_media <= 20 and Intervalo_limpeza == 5):
#   K = 225


# elif (Temperatura_media >= 21 and Intervalo_limpeza == 1):
#   K = 57

# elif (Temperatura_media >= 21 and Intervalo_limpeza == 2):
#   K = 97

# elif (Temperatura_media >= 21 and Intervalo_limpeza == 3):
#   K = 137

# elif (Temperatura_media >= 21 and Intervalo_limpeza == 4):
#   K = 177

# elif (Temperatura_media >= 21 and Intervalo_limpeza == 5):
#   K = 217
  

# Volume_util = 1000 + Np * (C * T + K + Lf)

# print("Contribuicao por unidade = " + str(C))
# print("Numero de pessoas = " + str(Np))
# print("Contribuicao de lodo fresco = " + str(Lf))
# print("Contribuicao diaria = " + str(Cd))
# print("Tempo de detencao = " + str(T) + " horas")
# print("Taxa de acumulacao total de lodo = " + str(K))
# print("Intervalo de limpezas = " + str(Intervalo_limpeza))
# print("Volume util = " + str(Volume_util) + " litros")

"""Filtro Anaeróbio

"""

Edificacao = 'Fabrica em Geral' #@param ["Selecione...", "Residencia", "Alojamento Provisorio" , "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais" , "Escolas ou locais de longa permanencia" , "Bares", "Restaurantes e similares", "Cinemas, teatros e locais de curta permanencia" , "Sanitarios Publicos" ]

if (Edificacao == "Residencia", "Alojamento Provisorio", "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais", "Escolas ou locais de longa permanencia"): 
  Numero_pessoas =  5#@param {type:"number"}

elif (Edificacao == "Restaurantes e similares", "Bares"):
  Numero_refeicoes = 5#@param {type:"number"}

elif (Edificacao == "Cinema, teatros e locais de curta permanencia"):
  Numero_lugares = 5#@param {type:"number"}

elif (Edificacao == "Sanitarios Publicos"):
  Numero_bacias_sanitarias = 5#@param {type:"number"}


Np = Numero_pessoas
C = "Valor Invalido"


if(Edificacao == "Residencia"):
  C = 200
  Lf = 1

elif(Edificacao == "Alojamento Provisorio"):
  C = 80
  Lf = 1

elif(Edificacao == "Fabrica em Geral"):
  C = 70
  Lf = 0.3

elif(Edificacao == "Escritorio"):
  C = 50
  Lf = 0.2

elif(Edificacao == "Edificios Publicos ou Comerciais"):
  C = 50
  Lf = 0.2

elif(Edificacao == "Escolas ou locais de longa permanencia"):
  C = 50
  Lf = 0.2

elif(Edificacao == "Bares"):
  C = 6
  Lf = 0.1

elif(Edificacao == "Restaurantes e similares"):
  C = 25
  Lf = 0.1

elif(Edificacao == "Cinemas, teatros e locais de curta permanencia"):
  C = 2
  Lf = 0.02

elif(Edificacao == "Sanitarios Publicos"):
  C = 480
  Lf = 4


Cd = C * Numero_pessoas



if (Cd <= 1500):
  T = 24

elif (Cd >= 1501 and Cd <= 3000):
  T = 22

elif (Cd >= 3001 and Cd <= 4500):
  T = 20

elif (Cd >= 4501 and Cd <= 6000):
  T = 18

elif (Cd >= 6001 and Cd <= 7500):
  T = 16

elif (Cd >= 7501 and Cd <= 9000):
  T = 14

elif (Cd >= 9001):
  T = 12

Volume_util = 1.60  * Np * C * T

Volume_cubico = Volume_util / 1000
Secao_horizontal = Volume_cubico/1.80


print("Volume util = " + str(Volume_util) + " litros")
print("Seçao horizontal =" + str(round(Secao_horizontal, 2)) + "m²")

"""Sumidouro/Vala de infiltração

"""

Edificacao = 'Fabrica em Geral' #@param ["Selecione...", "Residencia", "Alojamento Provisorio" , "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais" , "Escolas ou locais de longa permanencia" , "Bares", "Restaurantes e similares", "Cinemas, teatros e locais de curta permanencia" , "Sanitarios Publicos" ]

if (Edificacao == "Residencia", "Alojamento Provisorio", "Fabrica em Geral", "Escritorio", "Edificios Publicos ou Comerciais", "Escolas ou locais de longa permanencia"): 
  Numero_pessoas =  5#@param {type:"number"}

elif (Edificacao == "Restaurantes e similares", "Bares"):
  Numero_refeicoes = 5#@param {type:"number"}

elif (Edificacao == "Cinema, teatros e locais de curta permanencia"):
  Numero_lugares = 5#@param {type:"number"}

elif (Edificacao == "Sanitarios Publicos"):
  Numero_bacias_sanitarias = 5#@param {type:"number"}


Numero_pessoas = int(Numero_pessoas)

Coeficiente_percolacao =  270#@param {type:"number"}
Coeficiente_percolacao = float(Coeficiente_percolacao)

Np = Numero_pessoas
C = "Valor Invalido"
Ci =  Coeficiente_percolacao


if(Edificacao == "Residencia"):
  C = 200

elif(Edificacao == "Alojamento Provisorio"):
  C = 80

elif(Edificacao == "Fabrica em Geral"):
  C = 70

elif(Edificacao == "Escritorio"):
  C = 50

elif(Edificacao == "Edificios Publicos ou Comerciais"):
  C = 50
 
elif(Edificacao == "Escolas ou locais de longa permanencia"):
  C = 50

elif(Edificacao == "Bares"):
  C = 6

elif(Edificacao == "Restaurantes e similares"):
  C = 25

elif(Edificacao == "Cinemas, teatros e locais de curta permanencia"):
  C = 2

elif(Edificacao == "Sanitarios Publicos"):
  C = 480

V = C*Np

A = V/Ci

print("Área de infiltração necessária = " + str(A) + "m²")